name: foodviewer
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  
  supabase_flutter: ^2.5.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  shared_preferences: ^2.1.1
  permission_handler: ^12.0.1
  provider: ^6.1.2
  uuid: ^4.3.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  android_alarm_manager_plus: ^5.0.0
  connectivity_plus: ^7.0.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  flutter_dotenv: ^6.0.0
  workmanager: ^0.9.0+3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # APK / iOS ikon üretimi için
  flutter_launcher_icons: ^0.13.1


# 💠 İKON AYARLARI
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2a9a43"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - env.txt
    - assets/video/
